project_name: hetki

before:
  hooks:
    - go mod tidy

builds:
  - id: hetki
    main: .
    binary: hetki
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/MSmaili/hetki/cmd.Version={{.Version}}
      - -X github.com/MSmaili/hetki/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/MSmaili/hetki/cmd.BuildDate={{.Date}}

archives:
  - id: hetki
    format: binary
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Sign the checksums file with GPG (optional, requires GPG key)
# Uncomment the following to enable GPG signing:
# signs:
#   - artifacts: checksum
#     cmd: gpg
#     args:
#       - --batch
#       - --local-user
#       - "{{ .Env.GPG_FINGERPRINT }}"
#       - --output
#       - "${signature}"
#       - --detach-sign
#       - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: MSmaili
    name: hetki
  draft: false
  prerelease: auto
