version: 2

project_name: hetki

builds:
  - id: hetki
    main: .
    binary: hetki
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -buildid=
      - -X github.com/MSmaili/hetki/cmd.Version=v{{.Version}}
      - -X github.com/MSmaili/hetki/cmd.GitCommit={{.FullCommit}}
      - -X github.com/MSmaili/hetki/cmd.BuildDate={{.CommitDate}}

archives:
  - id: hetki
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: MSmaili
    name: hetki
  draft: false
  prerelease: auto
